### ISSUE TITLE
Error due composer install

### ISSUE THREAD

**Issue by StalkAlex** [dmstr/phd5-app#1]
Tried to run master's branch.  And got this error
![default](https://cloud.githubusercontent.com/assets/2943154/22972134/3b1fbcd6-f39a-11e6-9111-8b96534bb128.png)

**Comment by schmunk42** [comment]
Was this on a fresh installation?

As a workaround: Can you manually remove the folder in question? Did you make changes there?

**Comment by StalkAlex** [comment]
Yes, I just cloned your repo and `make all` straight away.  It turned out I should 've run composer install on host machine firstly. After long installation I was able to run template as `make all`.  I think it would be nice if you take it into readme eventually.

**Comment by schmunk42** [comment]
I feel your pain ... out of curiosity, what are you using for your Docker Host ... I can see `vagrant@localhost` - what's your host and guest OS?

Sidenote: You can ~~~always~~~ most of the time run `composer install` on your host, but `update` is not recommended.
Running the initial install natively definitely speeds up things.

**Comment by StalkAlex** [comment]
Yep, this is kind of a pain in the known place.... as host OS we're using Centos installed on Esxi vSphere, and all dev's machine are windows + vagrant + vsphere plugin to communicate to host os. This was quite working until docker came...)

**Comment by schmunk42** [comment]
Closing, since this should be working much better now. 

Please see also https://docs.docker.com/docker-for-mac/osxfs-caching/ for some hints how to setup filesystems with Docker.

**Comment by StalkAlex** [comment]
A lot have changed since I opened this issue, there are now such problems now. I'll check info, thanks!
