### ISSUE TITLE
SEO Settings

### ISSUE THREAD

**Issue by eluhr** [dmstr/phd5-app#17]
https://github.com/dmstr/phd5-app/blob/1167298b86295ccf6ca615dc90045e1f48c8966b/src/views/layouts/main.php#L44

@schmunk42 Maybe we have to change this line into `$route = yii\helpers\Url::to('');` or something similar.

If I am page e.g. `/frontend/default/index`, the `$route` would be `/<language>/frontend/frontend/default/index` because `\Yii::$app->controller->action->uniqueId` returns the unique id and not the current route (prefixed with a slash).
So to create a setting for with 'app.seo.titles', 'app.seo. descriptions', or  'app.seo. keywords' set as section will require an key like `/<language>/frontend/frontend/default/index` to work.

When we use ` yii\helpers\Url::to('')` as the key for this setting, we also have the advantage that page with the same route but different params can have its own 'SEO Settings'.

**Comment by schmunk42** [comment]
I think we should get rid of SEO stuff in settings completely.

Here's a branch in "pages" https://github.com/dmstr/yii2-pages-module/tree/feature/2.x-virtual-route which is related to this topic.

**Comment by eluhr** [comment]
https://github.com/dmstr/yii2-backend-module/pull/10
