### ISSUE TITLE
Stream logs in console yii application

### ISSUE THREAD

**Issue by StalkAlex** [dmstr/phd5-app#2]
It kind of usefull to have all logs in docker, but, for example, sometimes there is a situation when you need to do something manually in yii application inside container and all logs are getting into console together with appropriate output from commands. So how to deal with it?

**Comment by schmunk42** [comment]
Added some docs http://phd.dmstr.io/en/docs/guide/tutorials/logging.md

**Comment by StalkAlex** [comment]
Thanks!
