### ISSUE TITLE
Error during tests "make all"

### ISSUE THREAD

**Issue by motin** [dmstr/phd5-app#3]
```
tests$ make all
/Applications/Xcode.app/Contents/Developer/usr/bin/make version build
8052fb1
#
# Building images from docker-compose definitions
#
docker-compose build --pull
ERROR: The Compose file is invalid because:
Service php has neither an image nor a build context specified. At least one must be provided.
make[1]: *** [build] Error 1
make: *** [all] Error 2
```

**Comment by schmunk42** [comment]
I guess you need to run `make init` in the root directory first. I've updated the docs here: https://github.com/dmstr/phd5-docs/commit/77373676be934fdfef1ae3a67e94c23d87d2ac22

But I'll also try to fix this, so I keep this one open.

Thanks for reporting!

**Comment by schmunk42** [comment]
Fixed since a while, makes no sense to completely separate the initialization task for dev and test.
