### ISSUE TITLE
Using twbs 4.0.0 alpha4

### ISSUE THREAD

**Issue by philippfrenzel** [dmstr/phd5-app#4]
Hi,

by trying to use yii2/bootstrap2.1@dev it's not possible to update composer as the filemanager widgets are breaking compatibility ...

Any idea on how to sove this?

Thanks and cheers, Philipp

**Comment by Quexer69** [comment]
Hi Philipp,

could you please post the composer output?

**Comment by philippfrenzel** [comment]
bash-4.3# composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)                
Your requirements could not be resolved to an installable set of packages.   

  Problem 1
    - dmstr/yii2-filemanager-widgets 0.6.0-beta2 requires hrzg/yii2-filefly-module ^0.5.0 -> no matching package found.
    - dmstr/yii2-filemanager-widgets 0.6.0-beta1 requires hrzg/yii2-filefly-module ^0.5.0 -> no matching package found.
    - Conclusion: remove dmstr/yii2-filemanager-widgets 0.6.11
    - Conclusion: don't install dmstr/yii2-filemanager-widgets 0.6.11
    - Conclusion: don't install dmstr/yii2-filemanager-widgets 0.6.10
    - Conclusion: don't install dmstr/yii2-filemanager-widgets 0.6.9
    - Conclusion: don't install dmstr/yii2-filemanager-widgets 0.6.8
    - Conclusion: don't install dmstr/yii2-filemanager-widgets 0.6.7
    - Conclusion: don't install dmstr/yii2-filemanager-widgets 0.6.6
    - Conclusion: don't install dmstr/yii2-filemanager-widgets 0.6.5
    - Conclusion: don't install dmstr/yii2-filemanager-widgets 0.6.4
    - Conclusion: don't install dmstr/yii2-filemanager-widgets 0.6.3
    - Conclusion: don't install dmstr/yii2-filemanager-widgets 0.6.2
    - Conclusion: don't install dmstr/yii2-filemanager-widgets 0.6.1
    - Conclusion: don't install dmstr/yii2-filemanager-widgets 0.6.0
    - Conclusion: don't install dmstr/yii2-filemanager-widgets 0.6.0-rc2
    - Conclusion: don't install dmstr/yii2-filemanager-widgets 0.6.0-rc1
    - Installation request for yiisoft/yii2-bootstrap ^2.1.0@dev -> satisfiable by yiisoft/yii2-bootstrap[2.1.x-dev].
    - Installation request for dmstr/yii2-filemanager-widgets ^0.6.0 -> satisfiable by dmstr/yii2-filemanager-widgets[0.6.0, 0.6.0-beta1, 0.6.0-beta2, 0.6.0-beta3, 0.6.0-rc1, 0.6.0-rc2, 0.6.1, 0.6.10, 0.6.11, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.6.8, 0.6.9].
    - yiisoft/yii2-bootstrap 2.1.x-dev requires bower-asset/bootstrap ~4.0.0@alpha -> satisfiable by bower-asset/bootstrap[v4.0.0-alpha1, v4.0.0-alpha.2, v4.0.0-alpha.3, v4.0.0-alpha.4, v4.0.0-alpha.5, v4.0.0-alpha.6].
    - Can only install one of: bower-asset/bootstrap[v4.0.0-alpha1, v3.3.7].
    - Can only install one of: bower-asset/bootstrap[v4.0.0-alpha.2, v3.3.7].
    - Can only install one of: bower-asset/bootstrap[v4.0.0-alpha.3, v3.3.7].
    - Can only install one of: bower-asset/bootstrap[v4.0.0-alpha.4, v3.3.7].
    - Can only install one of: bower-asset/bootstrap[v4.0.0-alpha.5, v3.3.7].
    - Can only install one of: bower-asset/bootstrap[v4.0.0-alpha.6, v3.3.7].
    - dmstr/yii2-filemanager-widgets 0.6.0-beta3 requires bower-asset/bootstrap ^3.3.0 -> satisfiable by bower-asset/bootstrap[v3.3.7].
    - Conclusion: remove bower-asset/bootstrap v3.3.7

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by schmunk42** [comment]
Several extensions are not compatible with Bootstrap 3, I guess.

We can try to create a `feature/yii-2.1` branch and see what we'll need to change... PRs and feedback welcome.

**Comment by schmunk42** [comment]
I played around with 2.1 and there are some blockers for now.

Related https://github.com/yiisoft/yii2-debug/issues/238

**Comment by schmunk42** [comment]
Will be available from https://github.com/yiisoft/yii2-bootstrap4

**Comment by schmunk42** [comment]
You can use BS4 in the frontend, but the backend is tied to AdminLTE (BS3)
