### ISSUE TITLE
Switch to yii2-usuario?

### ISSUE THREAD

**Issue by schmunk42** [dmstr/phd5-app#8]
https://github.com/2amigos/yii2-usuario

**Comment by handcode** [comment]
Are there any migration plans from dektrium/yii2-user and rbac?

**Comment by philippfrenzel** [comment]
👍

**Comment by schmunk42** [comment]
@philippfrenzel Did you try the switch in an existing project?
@tonydspaniard Is there a migration plan? :)

**Comment by tonydspaniard** [comment]
@schmunk42 I need to write a migration guide not a plan, the plan should be written by those who wish to move to my humble module... 👍

**Comment by tonydspaniard** [comment]
https://yii2-usuario.readthedocs.io/en/latest/installation/migration-guide-from-dektrium-tools/

**Comment by schmunk42** [comment]
@tonydspaniard In general the change is pretty smooth already, just one thine we've noticed - but we need to investigate a bit more - if you have an application which has `user` and `profile` tables already, the migrations fail.

It would be cool if your module could separate it's migrations in a way that you're able to run migrations depending on a formerly exisiting `dektrium/yii2-user` module.
